platform :ios, '10.0'

#workspace文件名
workspace 'Pod管理.xcworkspace'

#主工程路径
project 'Pod管理/Pod管理.xcodeproj'

target 'Pod管理' do
  project 'Pod管理/Pod管理.xcodeproj'
  pod 'AFNetworking'
end

target 'WeatherAnimationProject' do
  project 'WeatherAnimationProject/WeatherAnimationProject.xcodeproj'
  
  target 'WeatherAnimationModule' do
    #pod 'AFNetworking'
  end
end
